language: ruby
rvm:
  - 2.2

env:
  - DB=pgsql

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database DevcampPortfolio_test;' -U postgres

install:
  - bundle install --jobs=3 --retry=3

script:
  - rake db:test:prepare
  - bundle exec rake

after_success:
  - coveralls